version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scripts/create-pull-request"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scripts/foundation-gen"
    schedule:
      interval: "weekly"